### ISSUE TITLE
BIOS files for OneMix 2s

### ISSUE THREAD

**Issue by RChadwick7** [balopez83/One_Mix_Yoga_4_Hackintosh#27]
I'm sure this isn't the right place for this, sorry. I noticed you had the BIOS files for the One Mix 3s. Do you by chance have the files for the One Mix 2s?

**Comment by balopez83** [comment]
Hi @RChadwick7 unfortunately I don't have the files for the One Mix 2s. I can't remember the user, but there was one that had put together a hackintosh page on Github for it and it might be worth reaching out to him.
