### ISSUE TITLE
[Question] Support for other 11th laptop CPU

### ISSUE THREAD

**Issue by FishCoding** [balopez83/One_Mix_Yoga_4_Hackintosh#30]
First, thank you for this efforts on the 11th gen of intel CPUs. 
The question would be if the kexts would work with the CPU i51135g7 straight or would require more efforts?

Thanks in advance :)

**Comment by balopez83** [comment]
@FishCoding if you are trying to use this on another OMY4 then yes, I believe it will work outright. Other 11th gen computers that are not OMY4's are far less likely to work as this EFI has special customizations that allow OMY4 specific hardware to work. If you are looking to get another non OMY4 working, you should use the config.plist as a template and work from there for the best possibility of success.
